Develop
QuiNovas/terraform-aws-dns-query-logs pull request #1
Opened 2019-03-08 11:31 UTC by vchinnakotla

2019-03-08 14:38 UTC, joseph-wortmann requested changes
You need to add an `outputs.tf` and a `locals.tf` file to this.

In the `outputs.tf` please output relevant information about the log group and the query log that you create (arn, etc.).

2019-03-08 14:38 UTC, joseph-wortmann commented on data.tf
> +    resources = ["arn:aws:logs:*:*:log-group:/aws/route53/*"]
Please change the resource to point _directly_ to the log-group that you created. This policy is too broad...

2019-03-08 14:38 UTC, joseph-wortmann commented on cloudwatch.tf
> +  name              = "/aws/route53/${var.hosted_zone_id}"
Is there a reason that we are using the hosted_zone_id and not the name of the hosted zone to name the log group? I think that the latter would be easier to read...

2019-03-11 10:26 UTC, vchinnakotla commented
Changes are made, please review.

2019-03-11 22:17 UTC, joseph-wortmann approved these changes

2019-03-11 22:17 UTC, joseph-wortmann commented on variables.tf
> +variable "domain_name" {
Don't make them pass this in. Use the aws_route53_hosted_zone data resource to get it instead.

2019-03-11 22:17 UTC, joseph-wortmann commented on data.tf
> +    resources = ["arn:aws:logs:*:*:log-group:/aws/route53/${var.domain_name}/*"]
Can't you get the actual arn from the log group you create in cloudwatch.tf?

2019-03-11 22:17 UTC, joseph-wortmann commented on variables.tf
> +  default     = 30
Make this 7 days

2019-03-11 22:18 UTC, merged